from enum import StrEnum


class ErrorCode(StrEnum):
    E_NO_PROFILE       = "E_NO_PROFILE"
    E_WP_AUTH          = "E_WP_AUTH"
    E_WP_UNREACHABLE   = "E_WP_UNREACHABLE"
    E_PAGE_NOT_FOUND   = "E_PAGE_NOT_FOUND"
    E_SECTION_NOT_FOUND = "E_SECTION_NOT_FOUND"
    E_INVALID_JSON     = "E_INVALID_JSON"
    E_TEMPLATE_NOT_FOUND = "E_TEMPLATE_NOT_FOUND"
    E_IMAGE_GEN_FAILED = "E_IMAGE_GEN_FAILED"
    E_NORMALIZE_PARTIAL = "E_NORMALIZE_PARTIAL"
    E_CRAWL_BLOCKED    = "E_CRAWL_BLOCKED"
    E_BACKUP_FAILED    = "E_BACKUP_FAILED"
    E_RESTORE_FAILED   = "E_RESTORE_FAILED"
    E_INTERNAL         = "E_INTERNAL"
